name: Build NG-GL4ES for Android

on:
 push:
 workflow_dispatch:

env:
 BUILD_TYPE: Release
 ANDROID_NDK_VERSION: "27.1.12297006"
 ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

jobs:
 build:
   runs-on: ubuntu-latest
   strategy:
     fail-fast: true

   steps:
   - uses: actions/checkout@v4

   - name: Setup environment
     run: |
       echo "ANDROID_SDK_ROOT=${{ env.ANDROID_SDK_ROOT }}" >> $GITHUB_ENV
       echo "${{ env.ANDROID_SDK_ROOT }}/cmdline-tools/latest/bin" >> $GITHUB_PATH
       sudo mkdir -p ${{ env.ANDROID_SDK_ROOT }}
       sudo chmod -R 777 ${{ env.ANDROID_SDK_ROOT }}

   - name: Install Android Command-line Tools
     run: |
       wget -q "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip";
       unzip -q commandlinetools-linux-*.zip -d ${{ env.ANDROID_SDK_ROOT }}/cmdline-tools
       mv ${{ env.ANDROID_SDK_ROOT }}/cmdline-tools/cmdline-tools ${{ env.ANDROID_SDK_ROOT }}/cmdline-tools/latest

   - name: Install Android NDK with sdkmanager
     run: |
       yes | sdkmanager --verbose \
         "ndk;${{ env.ANDROID_NDK_VERSION }}" \
         > /dev/null
     env:
       ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}

   - name: Set NDK root
     run: echo "ANDROID_NDK_ROOT=${{ env.ANDROID_SDK_ROOT }}/ndk/${{ env.ANDROID_NDK_VERSION }}" >> $GITHUB_ENV

   - name: Configure CMake
     run: |
       cmake -B build \
       -DANDROID_ABI=arm64-v8a \
       -DANDROID_PLATFORM=android-29 \
       -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
       -DANDROID_TOOLCHAIN=clang

   - name: Build
     run: cmake --build build --config Release --parallel $(nproc)

   - name: Strip
     run: |
       cd build
       $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip libng_gl4es.so
       
   - name: Upload
     uses: actions/upload-artifact@v4
     with:
       name: NG-GL4ES
       path: build/libng_gl4es.so
